<?php $titulo="Inserción de Datos en Tabla"; ?>
<?php include 'fragmentos/_header.php';?>

<h1><?php echo $titulo;?></h1>
<?php
$servername = "localhost";
$username = "root";
$password = "root";
$dbname = "dicampus";

// Crear conexión
$conn = new mysqli($servername, $username, $password, $dbname);

// Verificar si hay errores de conexión
if ($conn->connect_error) {
  die("Conexión fallida: " . $conn->connect_error);
}

// Generar datos aleatorios y ejecutar las consultas SQL para insertar las filas
for ($i = 1; $i <= 42; $i++) {
  // Generar nombres y apellidos aleatorios
  $lista_nombres =[ "Adrián",
  "Agustín",
  "Aitor",
  "Alba",
  "Alberto",
  "Alejandro",
  "Alfonso",
  "Alicia",
  "Alma",
  "Álvaro",
  "Amalia",
  "Amelia",
  "Ana",
  "Andrea",
  "Ángela",
  "Ángeles",
  "Anselmo",
  "Antonio",
  "Araceli",
  "Arancha",
  "Ariadna",
  "Arturo",
  "Ascensión",
  "Asier",
  "Aurora",
  "Axel",
  "Bárbara",
  "Beatriz",
  "Belén",
  "Benito",
  "Bernardo",
  "Blanca",
  "Borja",
  "Bruno",
  "Candela",
  "Carla",
  "Carlos",
  "Carmen",
  "Carolina",
  "Casandra",
  "Catalina",
  "Cayetano",
  "Cecilia",
  "Celia",
  "César",
  "Charo",
  "Clara",
  "Claudia",
  "Covadonga",
  "Cristina",
  "Daniel",
  "David",
  "Diego",
  "Dolores",
  "Elena",
  "Elisa",
  "Elvira",
  "Emilio",
  "Enrique",
  "Ernesto",
  "Esperanza",
  "Esteban",
  "Estela",
  "Eva",
  "Fátima",
  "Federico",
  "Felipe",
  "Félix",
  "Fernando",
  "Francisco",
  "Gabriel",
  "Gema",
  "Genaro",
  "Gerardo",
  "Germán",
  "Gloria",
  "Gonzalo",
  "Gracia",
  "Guadalupe",
  "Guillermo",
  "Gustavo",
  "Helena",
  "Héctor",
  "Hugo",
  "Inés",
  "Ignacio",
  "Iker",
  "Irene",
  "Isabel",
  "Isidro",
  "Ismael",
  "Jacinto",
  "Jacobo",
  "Jaime",
  "Javier",
  "Jesús",
  "Joaquín",
  "Jorge",
  "José",
  "Josefa",
  "Josefina",
  "Josué",
  "Juan",
  "Juana",
  "Julia",
  "Julián",
  "Julio",
  "Laura",
  "Lázaro",
  "Leandro",
  "Leonardo",
  "Lidia",
  "Lorena",
  "Lorenzo",
  "Lourdes",
  "Lucas",
  "Lucía",
  "Luis",
  "Luz",
  "Magdalena",
  "Manuel",
  "Marcelino",
  "Marcelo",
  "Marcos",
  "Margarita",
  "María",
  "Mariano",
  "Marina",
  "Mario",
  "Marta",
  "Martín",
  "Mateo",
  "Matilde",
  "Miguel",
  "Milagros",
  "Miriam",
  "Mónica",
  "Nacho",
  "Natalia",
  "Néstor",
  "Nicolás",
  "Noelia",
  "Nuria",
  "Octavio",
  "Olga",
  "Óscar",
  "Pablo",
  "Paloma",
  "Paola",
  "Patricia",
  "Paula",
  "Pedro",
  "Penélope",
  "Pilar",
  "Rafael",
  "Ramón",
  "Raquel",
  "Rebeca",
  "Reyes",
  "Ricardo",
  "Roberto",
  "Rodrigo",
  "Rogelio",
  "Rosa",
  "Rosario",
  "Rubén",
  "Salomé",
  "Salvador",
  "Samuel",
  "Sandra",
  "Santiago",
  "Sara",
  "Segismundo",
  "Silvia",
  "Sofía",
  "Sonia",
  "Soraya",
  "Susana",
  "Teresa",
  "Tomás",
  "Valentín",
  "Valeria",
  "Vanesa",
  "Vicente",
  "Victoria",
  "Víctor",
  "Virginia",
  "Ximena",
  "Yolanda",
  "Zoe"
];

  $lista_apellidos=[
    "Aguilar",
    "Alonso",
    "Alonso-Sánchez",
    "Amador",
    "Antúnez",
    "Arias",
    "Aranda",
    "Aznar",
    "Bellido",
    "Berenguer",
    "Bernal",
    "Blanco",
    "Bueno",
    "Calvo",
    "Campos",
    "Cano",
    "Cabrera",
    "Carrasco",
    "Carrasco-García",
    "Castillo",
    "Castillo-Garzón",
    "Cáceres",
    "Cervera",
    "Chacón",
    "Conejero",
    "Cornejo",
    "Correa",
    "Cortés",
    "Cruz",
    "Dávila",
    "Delgado",
    "Díaz",
    "Domínguez",
    "Esteban",
    "Fernández",
    "Ferrer",
    "Flores",
    "Fuentes",
    "Gallego",
    "Gallardo",
    "García",
    "Garrido",
    "Gil",
    "Gómez",
    "González",
    "Guerrero",
    "Gutiérrez",
    "Hernández",
    "Hidalgo",
    "Hinojosa",
    "Herrero",
    "Iglesias",
    "Jiménez",
    "Leiva",
    "Lara",
    "López",
    "López-Fando",
    "Lora",
    "Lorenzo",
    "Luna",
    "Martín",
    "Martínez",
    "Martínez-Campos",
    "Mendez",
    "Molina",
    "Montes",
    "Montiel",
    "Mora",
    "Morales",
    "Muñoz",
    "Navarro",
    "Núñez",
    "Oliva",
    "Ortega",
    "Ortiz",
    "Osorio",
    "Parra",
    "Pascual",
    "Pereira",
    "Peinado",
    "Peña",
    "Pérez",
    "Pérez-Solero",
    "Pinto",
    "Prieto",
    "Ramírez",
    "Ramos",
    "Reyes",
    "Rivas",
    "Rodríguez",
    "Rojas",
    "Romero",
    "Rosales",
    "Rubio",
    "Ruiz",
    "Sáez",
    "Sánchez",
    "Sánchez-Garrido",
    "Santana",
    "Santos",
    "Segura",
    "Serrano",
    "Soria",
    "Soto",
    "Toscano",
    "Torres",
    "Torrijos",
    "Tudela",
    "Valverde",
    "Vargas",
    "Vázquez",
    "Vega",
    "Velasco",
    "Vidal",
    "Villa",
    "Zamora",
    "Zulaica"
  ];

  //$nombre = "Alumno " . $i;
  $nombre =$lista_nombres[rand(0,count($lista_nombres)-1)];
  $apellidos =$lista_apellidos[rand(0,count($lista_apellidos)-1)]. " ".$lista_apellidos[rand(0,count($lista_apellidos)-1)];
  
  // Generar ciudades aleatorias
  $ciudades =[
  "Madrid",
  "Barcelona",
  "Valencia",
  "Sevilla",
  "Zaragoza",
  "Málaga",
  "Murcia",
  "Palma de Mallorca",
  "Las Palmas de Gran Canaria",
  "Bilbao",
  "Alicante",
  "Córdoba",
  "Valladolid",
  "Vigo",
  "Gijón",
  "La Coruña",
  "Granada",
  "Vitoria-Gasteiz",
  "Elche",
  "Santa Cruz de Tenerife",
  "Oviedo",
  "Badalona",
  "Cartagena",
  "Tarragona",
  "Jerez de la Frontera",
  "Sabadell",
  "Mostoles",
  "Alcalá de Henares",
  "Pamplona",
  "Fuenlabrada",
  "Almería",
  "San Sebastián",
  "Getafe",
  "Santander",
  "Castellón de la Plana",
  "Burgos",
  "Albacete",
  "Alcorcón",
  "Logroño",
  "Badajoz",
  "Salamanca",
  "Huelva",
  "Marbella",
  "Lleida",
  "Dos Hermanas",
  "Torrevieja",
  "Mataró",
  "León",
  "Cádiz",
  "Santa Coloma de Gramenet",
  "Algeciras",
  "Parla",
  "Jaén",
  "Torrejón de Ardoz",
  "Ourense",
  "Alcobendas",
  "Reus",
  "Telde",
  "Barakaldo",
  "Lugo",
  "Santiago de Compostela",
  "Cáceres",
  "Lorca",
  "San Fernando",
  "Manresa",
  "Avilés",
  "Irun"];

  $ciudad = $ciudades[rand(0,count($ciudades)-1)];

  // Generar fechas de nacimiento aleatorias
  $anio = rand(1990, 2005);
  $mes = rand(1, 12);
  $dia = rand(1, 28);
  $fecha_nacimiento = date('Y-m-d', mktime(0, 0, 0, $mes, $dia, $anio));
  
  // Generar nombres de archivo aleatorios para las fotos
  $foto = "foto" . rand(1,16) . ".png";
  
  // Consulta SQL para insertar una fila en la tabla "alumnos"
  $sql = "INSERT INTO alumnos (nombre, apellidos, ciudad, fecha_nacimiento, foto)
  VALUES ('$nombre', '$apellidos', '$ciudad', '$fecha_nacimiento', '$foto')";
  
  // Ejecutar la consulta SQL
  if ($conn->query($sql) === TRUE) {
    echo "Fila $i insertada correctamente con $nombre, $apellidos, $ciudad, $fecha_nacimiento, $foto <br>";
  } else {
    echo "Error al insertar la fila $i: " . $conn->error . "<br>";
  }
}

// Cerrar la conexión
$conn->close();
?>


<?php include 'fragmentos/_footer.php';?>